# compose/ca.yml - CA-only services for certificate re-enrollment
# Usage: docker-compose -f compose/ca.yml up -d

networks:
  fabric_net:
    name: fabric_real_estate_net

services:
  # Orderer Org CA
  ca.ordererorg.example.com:
    container_name: ca.ordererorg.example.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION:-latest}
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer-org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tls-key.pem
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 10054'
    volumes:
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric_net

  # OrgProp CA
  ca.orgprop.example.com:
    container_name: ca.orgprop.example.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION:-latest}
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-orgprop
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tls-key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 7054'
    volumes:
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgProp:/etc/hyperledger/fabric-ca-server
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgProp:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric_net

  # OrgTenant CA
  ca.orgtenant.example.com:
    container_name: ca.orgtenant.example.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION:-latest}
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-orgtenant
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tls-key.pem
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 8054'
    volumes:
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgTenant:/etc/hyperledger/fabric-ca-server
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgTenant:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric_net

  # OrgLandlord CA
  ca.orglandlord.example.com:
    container_name: ca.orglandlord.example.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION:-latest}
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-orglandlord
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tls-key.pem
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 9054'
    volumes:
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgLandlord:/etc/hyperledger/fabric-ca-server
      - /opt/fabric/fabric-real-estate-network/organizations/fabric-ca/orgLandlord:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric_net